# Generated by Django 3.2 on 2023-01-28 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0002_food_userfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
